<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZipCodeAndDelivery\Module'                        => __DIR__ . '/Module.php',
    'ZipCodeAndDelivery\Controller\SkeletonController' => __DIR__ . '/src/ZipCodeAndDelivery/Controller/ZipCodeController.php',
    'ZipCodeAndDelivery\Framework\TestCase'        => __DIR__ . '/tests/ZipCodeAndDelivery/Framework/TestCase.php',
    'ZipCodeAndDelivery\SampleTest'                => __DIR__ . '/tests/ZipCodeAndDelivery/SampleTest.php',
);